name: 'setup-renv'
description: 'Action to restore & cache R packages from renv.lock'
inputs:
  cache-version:
    description: 'The version of the cache. Change this to bust cache & trigger storing a new cache.'
    required: true
    default: 1
  lock-file: 
    description: 'Relative path to the renv.lock file.'
    required: true
    default: 'renv.lock'
runs:
  using: 'composite'
  steps:
      - name: Set RENV_PATHS_ROOT
        shell: bash
        run: |
          echo 'RENV_PATHS_ROOT=${{ runner.temp }}/renv' >> $GITHUB_ENV
      - name: Install and activate renv
        shell: Rscript {0}
        run: |
          paste("activated via ./renv & ./.Rprofile")
      - name: Get R and OS version
        id: get-version
        shell: Rscript {0}
        run: |
          cat("##[set-output name=os-version;]", sessionInfo()$running, "\n", sep = "")
          cat("##[set-output name=r-version;]", R.Version()$version.string, sep = "")
      - name: Restore {renv} package cache
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{ inputs.cache-version }}-${{ hashFiles(inputs.lock-file) }}
          restore-keys: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{ inputs.cache-version }}-
      - name: Restore packages from renv.lock file
        shell: Rscript {0}
        run: renv::restore("${{ inputs.lock-file }}")