# Workflow derived from # https://github.com/r-lib/actions/blob/v2-branch/examples/pkgdown.yaml

name: pkgdown-template
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:
jobs:
  pkgdown:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        r: ['release']
    # Only runs PR jobs concurrently & uses same group as other ghpages jobs
    # PR jobs run in their own branch & do not deploy anything - so we assume they can run concurrently
    concurrency:
      group: ghpages-${{ github.event_name != 'pull_request' || github.run_id }}
      cancel-in-progress: true
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          use-public-rspm: true
      - uses: prncevince/actions/setup-renv@main
      - name: Install libcurl on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
      - name: Restore packages from lock file
        shell: bash
        run: |
          cp setup-pkgdown/renv.lock .
          Rscript -e 'renv::restore()'
      - name: Build site
        shell: Rscript {0}
        run: pkgdown::build_site_github_pages(dest_dir = "docs/pkgdown", install = T)
      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ./docs/setup-pkgdown
          target-folder: setup-pkgdown