# Workflow derived from:
# https://github.com/r-lib/actions/blob/v2-branch/examples/pkgdown.yaml
# https://github.com/r-lib/actions/tree/v2/setup-renv
# https://github.com/actions/cache/blob/main/examples.md#r---renv
# https://github.com/jdjohn215/milwaukee-weather/tree/main/.github/workflows

name: renv-template
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:
jobs:
  setup-renv:
    name: ${{ matrix.os }} (${{ matrix.r }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        - {os: ubuntu-latest, r: 'release'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          # don't reinstall R
          install-r: false
          # use RStudio's CRAN mirror with precompiled binaries
          use-public-rspm: true
      - uses: prncevince/actions/setup-renv@main
